{{- if .Values.curator.enabled }}
{{- if or .Capabilities.APIVersions.Has "batch/v1beta1" .Capabilities.APIVersions.Has "batch/v2alpha1" -}}
apiVersion: {{ template "cronjob.apiVersion" $ }}
kind: CronJob
metadata:
  name: {{ template "fullname" . }}-curator
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  schedule: {{ .Values.curator.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curator
            image: "{{ .Values.image.curator.repository }}:{{ .Values.image.curator.tag }}"
            imagePullPolicy: {{ .Values.image.curator.pullPolicy }}
            args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: {{ template "fullname" . }}-curator-config
          restartPolicy: OnFailure
{{- end }}
{{- end }}
