{{- if .Values.metrics.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-metrics
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
    role: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
     component: {{ template "fullname" . }}
     role: metrics
  template:
    metadata:
      labels:
        component: {{ template "fullname" . }}
        role: metrics
    spec:
      containers:
      - name: metrics
        image: "{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}"
        imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
        resources:
{{ toYaml .Values.metrics.resources | indent 12 }}
        args:
          - -es.uri=http://{{ template "fullname" . }}:{{ .Values.service.httpPort }}
          - -es.all
          - -es.indices
        ports:
        - containerPort: 9108
          name: metrics
          protocol: TCP
{{- end }}
